### PR TITLE
Fix issuea all

### LINKED ISSUE #143: Issue.all should return all issues
According to [JIRA docs](https://docs.atlassian.com/jira/REST/latest/#api/2/search-search) for **search** method it returns only _maxResults_ of issues (that equals to 50 by default and cannot be safely overridden, results may be truncated).

I suppose it should be either renamed to something like _first_fifty_issues_ or load issues iteratively in several requests using _total_ value returned in response.

### PR DESCRIPTION
**Pull request by mtrepanier**
This should return ALL issues as it says it will.
Keeping count of the size of the result I currently have and then just appending to the array to return.
Setting a max result is optional but I did it anyway.
closes #143

ref: https://github.com/sumoheavy/jira-ruby/pull/174

### CODE REVIEW

File: lib/jira/resource/issue.rb [hunk 1]
```diff
@@ -40,12 +40,21 @@ class Issue < JIRA::Base
...
+        loop do
+          url = client.options[:rest_base_path] +
+                "/search?expand=transitions.fields&maxResults=#{max_results}&startAt=#{start_at}"
+          response = client.get(url)
+          json = parse_json(response.body)
+          json['issues'].map do |issue|
+            result.push(client.Issue.build(issue))
+          end
+          break if json['issues'].size == 0
+          start_at += json['issues'].size
```
Comment (mtrepanier) [inline lib/jira/resource/issue.rb]: In that loop, instead of making a request each time to see if there's data still available, I can leverage the use of the meta data contained in the response from jira

```
"expand": "schema,names",
"startAt": 0,
"maxResults": 1000,
"total": 11
```

So if `startAt + total` is greater then `maxResults` I make the request if not, no request.

Then after that I can create a new test to test that spec.

**Comment by mtrepanier** [comment]
@SimonMiaou for review
